### ISSUE TITLE
Recovering Data from Ethoscopes

### ISSUE THREAD

**Issue by zzaidi148** [gilestrolab/ethoscope#157]
Hello All!

I do believe this process is possible but haven't really found any documentation on it. So, I am currently running the node software on a virtual box vm of manjaro linux and it has been running great. However, over the weekend, for whatever reason, my host machine decided to restart and the virtual box vm did not rerun the program after the restart(the node didn't start). Looking at the data I have now, the ethoscopes have backed up the current experiment that is currently going on and have continued tracking. However, I am not able to access the experiment prior to this one that I ended the day before starting this current experiment. I do believe there should be a way to get the results directly off the ethoscopes, so I wanted to ask if anyone has any experience with that. Also, if anyone has any alternatives to running the node on a vm while still being able to analyze data in RStudio while an experiement is ongoing or any insight from your own setup that would be much appreciated! Thank you!

**Comment by ggilestro** [comment]
At the moment, each ethoscope uses the same database name meaning that every time you start an experiment the previous data are deleted and overwritten (this is not ideal and will change soon - the code has already been predisposed for the change but I have not committed it yet). 

That means that if you restarted a new experiment, you cannot really retrieve those data that you did not backup, sorry.
If you have not started a new experiment, the data should still be in the ethoscope and they should be automatically retrieved as you connect the ethoscope to the network.

However, if you are running a slightly older version of the software, chances are that you have an option that exports the database to the sd card as SQL file at the end of each experiment. That option should not currently active on the latest version of `dev` because it created too much sudden card I/O access.
